### ISSUE TITLE
ModuleNotFoundError: No module named 'wraps.primitives'

### ISSUE THREAD

**Issue by DelofJ** [nekitdev/iters#67]
I get this error on Python 3.11.9, I'm using a virtual environment 
And it is the latest version of iters aka 0.18.0
```
Traceback (most recent call last):
  File "c:\Users\DelofJ\Code Projects\Geometry Dash API\main.py", line 19, in <module>
    import iters
  File "C:\Users\DelofJ\Code Projects\Geometry Dash API\.venv\Lib\site-packages\iters\__init__.py", line 16, in <module>
    from iters.async_iters import (
  File "C:\Users\DelofJ\Code Projects\Geometry Dash API\.venv\Lib\site-packages\iters\async_iters.py", line 64, in <module>
    from wraps.primitives.option import Option, Some
ModuleNotFoundError: No module named 'wraps.primitives'
```

**Comment by DelofJ** [comment]
Issue also related to https://github.com/nekitdev/async-extensions/issues/15

**Comment by DelofJ** [comment]
I was there was apparently a PR fixing the issue https://github.com/nekitdev/iters/pull/66
Will it eventually be merged ?

**Comment by ISviterI** [comment]
hi, i know how to fix it.
put this in terminal:
pip uninstall wraps iters
pip install wraps==0.1.0 iters==0.1.0 gd.py
